### ISSUE TITLE
Ошибка при выборе Почты России: Uncaught TypeError: Cannot read property 'street' of null

### ISSUE THREAD

**Issue by aiiddqd** [Yandex-Delivery/Cart-Widget#14]
Использую пример из этого репа. Только свой скрипт из Кабинета вставил.

Сценарий:
- если выбираю Самовывоз - все ок. Работает как надо.
- если выбираю Почту России - то при нажатии на кнопку Выбрать, форма выбора не закрывается. При этом цена проставляется. 

В консоли пишет ошибку:
```
Uncaught TypeError: Cannot read property 'street' of null
    at CartWidgetConfig.onDeliveryChange (checkout.html:57)
    at CartWidgetConfig.BaseConfig.callHook (baseConfig.js?v=1.1.8:104)
    at CartWidget.deliveryChangeHandler (cartWidget.js?v=1.1.8:164)
    at HTMLDocument.<anonymous> (cartWidget.js?v=1.1.8:57)
    at HTMLDocument.dispatch (jquery.modified.js?v=1.1.8:3076)
    at HTMLDocument.elemData.handle (jquery.modified.js?v=1.1.8:2753)
    at Object.trigger (jquery.modified.js?v=1.1.8:2989)
    at HTMLDocument.<anonymous> (jquery.modified.js?v=1.1.8:3679)
    at Function.each (jquery.modified.js?v=1.1.8:648)
    at init.each (jquery.modified.js?v=1.1.8:270)
```

Снимок:
![image](https://user-images.githubusercontent.com/1852897/34074362-50ebf962-e2be-11e7-8289-decf43002a6b.png)

**Comment by aiiddqd** [comment]
Ошибка пропала

**Comment by PUUZOO** [comment]
Выдаёт такую же ошибку, победить никак не могу. 
Помогите) 
Вот мой код 
`
    
    <script type="text/javascript">

      ydwidget.ready(function(){
        ydwidget.initCartWidget({
          //получить указанный пользователем город
          'getCity': function () {

            
            var city = yd$('#billing_city').val();
            if (city) {
              return false;
            } else {
              return {value: city};
            }
            
           

          },

          //id элемента-контейнера
          'el': 'ydwidget',

          //общее количество товаров в корзине
          'totalItemsQuantity': function () { return cart.quantity },

          //общий вес товаров в корзине
          'weight': function () { return cart.weight },

          //общая стоимость товаров в корзине
          'cost': function () { return cart.cost },

          //габариты и количество по каждому товару в корзине
          'itemsDimensions': function () {return 
            <?php echo substr(json_encode($data_ship),1,-1); ?>
            // [10,15,10,2],
            // [20,15,5,1]
          },

          //объявленная ценность заказа. Влияет на расчет стоимости в предлагаемых вариантах доставки, для записи поля в заказ данное поле так же нужно передать в объекте order (поле order_assessed_value)
          'assessed_value': cart.cost,
          //Способы доставки. Влияют на предлагаемые в виджете варианты способов доставки.
          onlyDeliveryTypes: function(){return ['todoor','pickup','post']},
          //обработка автоматически определенного города
          'setCity': function (city, region) { yd$('#billing_city').val(region ? city + ', ' + region : city + ', '); console.log(yd$('#billing_city').val());},
          //обработка смены варианта доставки
          'onDeliveryChange': function (delivery) {
            //если выбран вариант доставки, выводим его описание и закрываем виджет, иначе произошел сброс варианта,
            //очищаем описание
            if (delivery) {

              var yd_params = [{
                'id': ydwidget.cartWidget.selectedDelivery.delivery.id,
                'delivery_service_id': ydwidget.cartWidget.selectedDelivery.delivery.delivery_service_id,
                'name': ydwidget.cartWidget.selectedDelivery.delivery.name,
                'unique_name': ydwidget.cartWidget.selectedDelivery.delivery.unique_name,
                'description': ydwidget.cartWidget.view.helper.getDeliveryDescription(delivery),
                'cost': ydwidget.cartWidget.selectedDelivery.costWithRules,
              }];         


              yd$('#yd_cost').val(ydwidget.cartWidget.selectedDelivery.costWithRules); //@TODO: do right
              yd$('#yd_params').val(JSON.stringify(yd_params)); //@TODO: do right


              if (ydwidget.cartWidget.selectedDelivery.type == "POST") {
                yd$('#billing_address_1').val(ydwidget.cartWidget.getAddress().street);
                yd$('#billing_address_2').val(ydwidget.cartWidget.getAddress().house);
                ydwidget.cartWidget.close();
              } else {
                // yd$(document).trigger('ydmyevent');
                ydwidget.cartWidget.close();
              }

              jQuery( 'form.checkout' ).trigger( 'update' );
              yd$('#delivery_description').text(ydwidget.cartWidget.view.helper.getDeliveryDescription(delivery));

            }
            else {
              yd$('#delivery_description').text('');
            }
          },
          'onLoad': function () {
            //при клике на радиокнопку, если это не радиокнопка "Яндекс.Доставка", сбрасываем выбранную доставку
            //в виджете
            yd$(document).on('click', 'input:radio[name="delivery"]', function () {
              if (yd$(this).not('#yd_delivery')) {
                ydwidget.cartWidget.setDeliveryVariant(null);
              }
            });

          },

          //снятие выбора с варианта доставки "Яндекс.Доставка" (настроенного в CMS)
          'unSelectYdVariant': function () { yd$('#yd_delivery').prop('checked', false) },

          //автодополнение
          'autocomplete': ['city', 'street', 'index'],
           'cityEl': '#billing_city',
           'streetEl': '#billing_address_1',
           'houseEl': '#billing_address_2',
           'indexEl': '#billing_postcode',

          'createOrderFlag': function () { 
            //console.log('Создан ордер в cookie');
            return true
          },

          'order': {
          //имя, фамилия, телефон, улица, дом, индекс
            'recipient_first_name': function () { return yd$('#billing_first_name').val() },
            'recipient_last_name': function () { return yd$('#billing_last_name').val() },
            'recipient_phone': function () { return yd$('#billing_phone').val() },
            'deliverypoint_street': function () { return yd$('#billing_address_1').val() },
            'deliverypoint_house': function () { return yd$('#billing_address_2').val() },
            'deliverypoint_index': function () { return yd$('#billing_postcode').val() },

            'order_items': <?php echo $ya_items ?>,
            'order_assessed_value': cart.cost,
            // 'order_items': function () {
            //   var items = [];
            //   items.push({
            //     'orderitem_name': 'Товар 1',
            //     'orderitem_quantity': 2,
            //     'orderitem_cost': 100
            //   });
            //   return items;
            // }
          },

          //id элемента для вывода ошибок валидации. Вместо него можно указать параметр onValidationEnd, для кастомизации
          //вывода ошибок
          'errorsEl': 'yd_errors',
          'runOrderCreation': function () { yd$('#place_order').click() }
        })
      })
      
      

    </script>`
